
require 'rake/clean'
require 'ffi'

FILES = {}

task :default => [:build, :compact]

def self.file_task(filename, opts, &block)
  name, dep = opts.is_a?(Hash) ? opts.to_a.first : [opts, nil]
  
  FILES[name] = filename
  CLEAN.include filename
  task name => filename
  
  if dep
    file filename => FILES[dep], &block
  else
    file filename, &block
  end
end

def cmd(string)
  fail "Command failed: #{string}" unless system(string)
end

file_task 'paho.mqtt.c.tar.gz', :download_tarball do
  version = "1.0.3"
  release = "https://github.com/eclipse/paho.mqtt.c/archive/v#{version}.tar.gz"
  cmd "wget -O #{FILES[:download_tarball]} #{release}"
end

file_task 'paho.mqtt.c', :download => :download_tarball do
  cmd "tar -zxf #{FILES[:download_tarball]}"
  cmd "mv paho.mqtt.c-* #{FILES[:download]}"
end

file_task "libpaho-mqtt3c.#{::FFI::Platform::LIBSUFFIX}", :build => :configure do
  cmd "/usr/bin/env sh -c 'cd #{FILES[:download]} && make'"
  cmd "cp #{FILES[:download]}/build/output/#{FILES[:build]} ."
end

task :compact => FILES[:build] do
  FILES.each do |key, filename|
    cmd "rm -rf #{filename}" unless key == :build
  end
end
